package com.lishun.im.bean;

import java.util.Date;

public class ImEmployeeSale {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_employee_sale.id
     *
     * @mbggenerated Sat Jul 02 17:16:13 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_employee_sale.specifications
     *
     * @mbggenerated Sat Jul 02 17:16:13 CST 2016
     */
    private String specifications;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_employee_sale.im_warehouse_id
     *
     * @mbggenerated Sat Jul 02 17:16:13 CST 2016
     */
    private String imWarehouseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_employee_sale.im_species_id
     *
     * @mbggenerated Sat Jul 02 17:16:13 CST 2016
     */
    private String imSpeciesId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_employee_sale.sale_price
     *
     * @mbggenerated Sat Jul 02 17:16:13 CST 2016
     */
    private Double salePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_employee_sale.num
     *
     * @mbggenerated Sat Jul 02 17:16:13 CST 2016
     */
    private Long num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_employee_sale.im_employee_id
     *
     * @mbggenerated Sat Jul 02 17:16:13 CST 2016
     */
    private String imEmployeeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_employee_sale.create_time
     *
     * @mbggenerated Sat Jul 02 17:16:13 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_employee_sale.pro_no
     *
     * @mbggenerated Sat Jul 02 17:16:13 CST 2016
     */
    private Long proNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_employee_sale.billing_by
     *
     * @mbggenerated Sat Jul 02 17:16:13 CST 2016
     */
    private String billingBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_employee_sale.count_price
     *
     * @mbggenerated Sat Jul 02 17:16:13 CST 2016
     */
    private Double countPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_employee_sale.is_price
     *
     * @mbggenerated Sat Jul 02 17:16:13 CST 2016
     */
    private Boolean isPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column im_employee_sale.remark
     *
     * @mbggenerated Sat Jul 02 17:16:13 CST 2016
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column im_employee_sale.id
     *
     * @return the value of im_employee_sale.id
     *
     * @mbggenerated Sat Jul 02 17:16:13 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column im_employee_sale.id
     *
     * @param id the value for im_employee_sale.id
     *
     * @mbggenerated Sat Jul 02 17:16:13 CST 2016
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column im_employee_sale.specifications
     *
     * @return the value of im_employee_sale.specifications
     *
     * @mbggenerated Sat Jul 02 17:16:13 CST 2016
     */
    public String getSpecifications() {
        return specifications;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column im_employee_sale.specifications
     *
     * @param specifications the value for im_employee_sale.specifications
     *
     * @mbggenerated Sat Jul 02 17:16:13 CST 2016
     */
    public void setSpecifications(String specifications) {
        this.specifications = specifications;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column im_employee_sale.im_warehouse_id
     *
     * @return the value of im_employee_sale.im_warehouse_id
     *
     * @mbggenerated Sat Jul 02 17:16:13 CST 2016
     */
    public String getImWarehouseId() {
        return imWarehouseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column im_employee_sale.im_warehouse_id
     *
     * @param imWarehouseId the value for im_employee_sale.im_warehouse_id
     *
     * @mbggenerated Sat Jul 02 17:16:13 CST 2016
     */
    public void setImWarehouseId(String imWarehouseId) {
        this.imWarehouseId = imWarehouseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column im_employee_sale.im_species_id
     *
     * @return the value of im_employee_sale.im_species_id
     *
     * @mbggenerated Sat Jul 02 17:16:13 CST 2016
     */
    public String getImSpeciesId() {
        return imSpeciesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column im_employee_sale.im_species_id
     *
     * @param imSpeciesId the value for im_employee_sale.im_species_id
     *
     * @mbggenerated Sat Jul 02 17:16:13 CST 2016
     */
    public void setImSpeciesId(String imSpeciesId) {
        this.imSpeciesId = imSpeciesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column im_employee_sale.sale_price
     *
     * @return the value of im_employee_sale.sale_price
     *
     * @mbggenerated Sat Jul 02 17:16:13 CST 2016
     */
    public Double getSalePrice() {
        return salePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column im_employee_sale.sale_price
     *
     * @param salePrice the value for im_employee_sale.sale_price
     *
     * @mbggenerated Sat Jul 02 17:16:13 CST 2016
     */
    public void setSalePrice(Double salePrice) {
        this.salePrice = salePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column im_employee_sale.num
     *
     * @return the value of im_employee_sale.num
     *
     * @mbggenerated Sat Jul 02 17:16:13 CST 2016
     */
    public Long getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column im_employee_sale.num
     *
     * @param num the value for im_employee_sale.num
     *
     * @mbggenerated Sat Jul 02 17:16:13 CST 2016
     */
    public void setNum(Long num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column im_employee_sale.im_employee_id
     *
     * @return the value of im_employee_sale.im_employee_id
     *
     * @mbggenerated Sat Jul 02 17:16:13 CST 2016
     */
    public String getImEmployeeId() {
        return imEmployeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column im_employee_sale.im_employee_id
     *
     * @param imEmployeeId the value for im_employee_sale.im_employee_id
     *
     * @mbggenerated Sat Jul 02 17:16:13 CST 2016
     */
    public void setImEmployeeId(String imEmployeeId) {
        this.imEmployeeId = imEmployeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column im_employee_sale.create_time
     *
     * @return the value of im_employee_sale.create_time
     *
     * @mbggenerated Sat Jul 02 17:16:13 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column im_employee_sale.create_time
     *
     * @param createTime the value for im_employee_sale.create_time
     *
     * @mbggenerated Sat Jul 02 17:16:13 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column im_employee_sale.pro_no
     *
     * @return the value of im_employee_sale.pro_no
     *
     * @mbggenerated Sat Jul 02 17:16:13 CST 2016
     */
    public Long getProNo() {
        return proNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column im_employee_sale.pro_no
     *
     * @param proNo the value for im_employee_sale.pro_no
     *
     * @mbggenerated Sat Jul 02 17:16:13 CST 2016
     */
    public void setProNo(Long proNo) {
        this.proNo = proNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column im_employee_sale.billing_by
     *
     * @return the value of im_employee_sale.billing_by
     *
     * @mbggenerated Sat Jul 02 17:16:13 CST 2016
     */
    public String getBillingBy() {
        return billingBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column im_employee_sale.billing_by
     *
     * @param billingBy the value for im_employee_sale.billing_by
     *
     * @mbggenerated Sat Jul 02 17:16:13 CST 2016
     */
    public void setBillingBy(String billingBy) {
        this.billingBy = billingBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column im_employee_sale.count_price
     *
     * @return the value of im_employee_sale.count_price
     *
     * @mbggenerated Sat Jul 02 17:16:13 CST 2016
     */
    public Double getCountPrice() {
        return countPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column im_employee_sale.count_price
     *
     * @param countPrice the value for im_employee_sale.count_price
     *
     * @mbggenerated Sat Jul 02 17:16:13 CST 2016
     */
    public void setCountPrice(Double countPrice) {
        this.countPrice = countPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column im_employee_sale.is_price
     *
     * @return the value of im_employee_sale.is_price
     *
     * @mbggenerated Sat Jul 02 17:16:13 CST 2016
     */
    public Boolean getIsPrice() {
        return isPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column im_employee_sale.is_price
     *
     * @param isPrice the value for im_employee_sale.is_price
     *
     * @mbggenerated Sat Jul 02 17:16:13 CST 2016
     */
    public void setIsPrice(Boolean isPrice) {
        this.isPrice = isPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column im_employee_sale.remark
     *
     * @return the value of im_employee_sale.remark
     *
     * @mbggenerated Sat Jul 02 17:16:13 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column im_employee_sale.remark
     *
     * @param remark the value for im_employee_sale.remark
     *
     * @mbggenerated Sat Jul 02 17:16:13 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}